---
abstract: 'Utilities for Gentoo::'
author:
  - 'Kent Fredric <kentfredric@gmail.com>'
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Gentoo-Util
no_index:
  directory:
    - inc
requires:
  Moose: 0.63
  Moose::Util::TypeConstraints: 0.63
  boolean: 0.2
  perl: 5.01
  version: 0.76
resources:
  license: http://dev.perl.org/licenses/
version: 0.1
